# Generated by Django 4.0.2 on 2022-03-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicevent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default='2006-10-25 14:30'),
            preserve_default=False,
        ),
    ]
