# Generated by Django 4.0.2 on 2022-03-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicevent', '0005_alter_contract_payment_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='signed',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
