# Generated by Django 4.0.2 on 2022-03-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epicevent', '0007_alter_client_company_name_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('client_id', 'contract_id')},
        ),
    ]
