# Generated by Django 4.0.2 on 2022-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220303_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('SALES', 'Sales'), ('SUPPORT', 'Support')], max_length=30, null=True),
        ),
    ]
